basePath: /
definitions:
  domain.Player:
    properties:
      created_at:
        type: string
      player_id:
        type: string
      player_name:
        type: string
      updated_at:
        type: string
    type: object
  handler.playerInterface:
    properties:
      player_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a game API.
  title: Game API
  version: "1.0"
paths:
  /player:
    get:
      consumes:
      - application/json
      description: Get details of all player
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Player'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all player
      tags:
      - Player
    post:
      consumes:
      - application/json
      description: Create a new player
      parameters:
      - description: Player Data
        in: body
        name: PlayerData
        required: true
        schema:
          $ref: '#/definitions/handler.playerInterface'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Player'
      security:
      - ApiKeyAuth: []
      summary: create a new player
      tags:
      - Player
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
